FROM ubuntu:20.04

RUN apt-get update && apt-get install -y \
    autoconf \
    bison \
    build-essential \
    curl \
    flex \
    git \
    libgmp3-dev \
    libmpc-dev \
    libmpfr-dev \
    libncurses5-dev \
    libusb-dev \
    unzip \
    wget
